/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Background: typeof import('./src/components/Background.vue')['default']
    FansTitle: typeof import('./src/components/FansTitle.vue')['default']
    FocusedInput: typeof import('./src/components/FocusedInput.vue')['default']
    Header: typeof import('./src/layouts/Header.vue')['default']
    Main: typeof import('./src/layouts/Main.vue')['default']
    NInput: typeof import('naive-ui')['NInput']
    NPopover: typeof import('naive-ui')['NPopover']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SuperChat: typeof import('./src/components/SuperChat.vue')['default']
  }
}
